### ISSUE TITLE
Block "discord.com/api/v6/science"

### ISSUE THREAD

**Issue by PhoenixDiscord** [khlam/discord-sandboxed#1]
Discord tracks its users by making the client send analytics data to them through the `/api/v6/science` and `/api/v6/track` endpoints. See https://luna.gitlab.io/discord-unofficial-docs/science.html

Also, Discord is planning to change its API, so I'd say that you should block these domains/endpoints:

- `discordapp.com/api/science`
- `discord.com/api/science`
- `discordapp.com/api/track`
- `discord.com/api/track`
- `discordapp.com/api/v*/science`
- `discord.com/api/v*/science`
- `discordapp.com/api/v*/track`
- `discord.com/api/v*/track`

(replace `*` with a regex or something to block numbers `1-99`)

**Comment by khlam** [comment]
This is an interesting problem!

I've addressed this in b4092c1fe7649c69b691d39fd4c931eee4f9bfc9. This whitelists requests to `/api/v6/channels/` (Discord's text channels) and blocks everything else. 

This works by inserting some Javascript into `<webview>` on creation that overrides `window.XMLHttpRequest.prototype.open`. If the destination address does not contain a sub-string in the whitelist it'll nullify the call.

We can verify this working if we open the developer tools after running the project. We see the client no longer sends requests to `/science`

**Before:**
![image](https://user-images.githubusercontent.com/4841220/86415571-54a09c80-bc7c-11ea-8e0b-a4ef2556a171.png)

**After b4092c1fe7649c69b691d39fd4c931eee4f9bfc9:**
![image](https://user-images.githubusercontent.com/4841220/86415730-c1b43200-bc7c-11ea-8f0a-fe1624c2ef8d.png)

Now I'm not sure if this actually makes the anyone "safer", because this approach (and this entire project) automatically executes client-side JS on behalf of the user which could increase an "attack's surface-area", namely, undiscovered malicious code in the project's source could automatically run inside the Discord container.

I'm not worried about this because the project is small and takes some technical knowledge to run.
I'll look to merge b4092c1fe7649c69b691d39fd4c931eee4f9bfc9 after I make the whitelist feature more flexible.
